### ISSUE TITLE
advice leetcode issues

### ISSUE THREAD

**Issue by MoonCheung** [ayoubzulfiqar/leetcode#1]
Hi, hello, I am a dart learner, suggest adding number sequence + leetcode topic is relatively easy to find

**Comment by ayoubzulfiqar** [comment]
@MoonCheung
Dear Coder. Do You want me to add the problem number along with Its name which is provided by leetcode or do You want me to add the prime number sequence (e.g 1,2,3,4,5,6,7,8,9............n)

**Comment by MoonCheung** [comment]
@ayoubzulfiqar  Hey, make sure leetcode provides the problem number

**Comment by ayoubzulfiqar** [comment]
@MoonCheung 
Thanks for your kind advice. After visiting every again problem each and every page to finds its number. I officially posted the problem number with its name inside the README file.
